GET {{baseUrl}}/api/acteurs/PA720892
Accept: application/json

###
GET {{baseUrl}}/api/acteurs?nom=Panot
Accept: application/json

###
GET {{baseUrl}}/api/acteurs?prenom=Mathilde
Accept: application/json

###
#TODO permettre la recherche sur nom et prénom
#GET {{baseUrl}}/api/acteurs?prenom=Mathilde&nom=Panot
#Accept: application/json
